### ISSUE TITLE
Panic error with latest version 0.10.8 -- panic: Malformed version: stable

### ISSUE THREAD

**Issue by nonus25** [ktr0731/evans#577] opened 2022-08-24 19:54 UTC
## Describe the bug

```panic: Malformed version: stable
                                                                
goroutine 33 [running]:                                                      
github.com/hashicorp/go-version.Must(...)                                               
        /Users/ktr/.ghq/pkg/mod/github.com/hashicorp/go-version@v1.4.0/version.go:102      
github.com/ktr0731/go-updater/brew.(*HomebrewClient).LatestTag(0xc000110030, {0x19cb448, 0xc0004e0180})
        /Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-updater@v0.1.5/brew/brew.go:66 +0x5aa
github.com/ktr0731/go-updater.(*Updater).Updatable(0xc000110060, {0x19cb448, 0xc0004e0180})
        /Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-updater@v0.1.5/updater.go:48 +0x3f
github.com/ktr0731/evans/app.checkUpdate({0x19cb448, 0xc0004e0180}, 0x1004d1d, 0xc0004a6140)
        /Users/ktr/.ghq/src/github.com/ktr0731/evans/app/update.go:64 +0x1a8
github.com/ktr0731/evans/app.runREPLCommand.func1()
        /Users/ktr/.ghq/src/github.com/ktr0731/evans/app/commands.go:269 +0x2c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/ktr/.ghq/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/ktr/.ghq/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

I am getting this error with the latest `evans` version 0.10.8 on MacOS

```
>  go version
go version go1.18.3 darwin/amd64
```

when installed `evans` 0.10.6 via `go install` all seems to be OK.

Regards
Auggie

**Comment by bombsimon** [comment] 2022-08-26 07:55
Seems to be a duplicate of #575 which has some workarounds until fixed.

**Comment by nonus25** [comment] 2022-08-26 08:24
@bombsimon by looking at the issue pointed by you #575 I agree that is looking same.

**Comment by nonus25** [comment] 2022-08-26 08:25
closing as a duplicate of #575

**Closed** 2022-08-26 08:24 UTC
Labels: bug
