### ISSUE TITLE
Installation in CentOS Linux

### ISSUE THREAD

**Issue by abhilash93** [ktr0731/evans#150] opened 2019-02-18 04:55 UTC
I tried to install EVANS in Centos and downloaded evans_linux_386.tar.gz file and unzip in linux using tar commands got a evans file but did not give and installation file.

I have tried downloading the code and doing the build but the make install failed.

Can you please help in installation steps on Centos Linux systems

**Comment by ktr0731** [comment] 2019-02-19 05:03
What is your system's architecture? (not i386?)
If it is not i386 architecture, you need to build from source code just you did.
You can build by following commands:

```
$ git clone https://github.com/ktr0731/evans
$ cd evans
$ git checkout v0.6.11
$ make build
```

Note that you need to install Go v1.11.0 or later.

**Comment by abhilash93** [comment] 2019-02-19 16:35
Thank you.
I have followed the steps and got this error when ran make build

go: verifying github.com/improbable-eng/grpc-web@v0.0.0-20181106071443-fbed44528bdc: checksum mismatch
        downloaded: h1:J3O4K0txQxRTJj9Ok0tbFKG+Pqariu4X1H++SkZdIgk=
        go.sum:     h1:e8oneEkZWv8cmBQlaeElsD63DN0/L1XX5nZKVbDBi1c=
make: *** [deps] Error 1

Do we have to do anything for this?

**Comment by abhilash93** [comment] 2019-02-19 19:44
I was able to by pass the above error now i see new error

golang.org/x/net v0.0.0-20181107234226-1c5f79cfb164: dir has been modified (/root/go/pkg/mod/golang.org/x/net@v0.0.0-20181107234226-1c5f79cfb164)
golang.org/x/sys v0.0.0-20181205085412-a5c9d58dba9a: dir has been modified (/root/go/pkg/mod/golang.org/x/sys@v0.0.0-20181205085412-a5c9d58dba9a)
make: *** [deps] Error 1

**Comment by ktr0731** [comment] 2019-02-20 01:32
Thank you for providing details.
According to [this issue](https://github.com/golang/go/issues/29278), the checksum is broken in pre-Go1.11.4.
Please upgrade your go binary to the latest version. In my environment, building with the latest Go worked fine.

**Comment by abhilash93** [comment] 2019-02-20 01:44
I have the latest  Go

go version
go version go1.11.4 linux/amd64

**Comment by ktr0731** [comment] 2019-02-20 01:53
Could you build with Go1.11.5?
By the way, if you are using linux/amd64, you can use [linux/amd64 release binary](https://github.com/ktr0731/evans/releases/download/0.6.11/evans_linux_amd64.tar.gz).

**Comment by abhilash93** [comment] 2019-02-20 02:13
I tried to update the go 
git clone https://github.com/udhos/update-golang
cd update-golang
sh update-golang.sh

It did not work.

I downloaded [linux/amd64 release binary](https://github.com/ktr0731/evans/releases/download/0.6.11/evans_linux_amd64.tar.gz).

tried to unzip and run make install
when i unzip
$tar -xzf evans_linux_amd64\ \(2\).tar.gz
$ls
$evans  evans_linux_amd64 (2).tar.gz

I am not getting all the file to install
Can you please let me know a process to use linux/amd64 and install

**Comment by ktr0731** [comment] 2019-02-20 02:28
We distribute only binary files in GitHub Releases.
So, you have to move the binary to a path where executable binaries are located.
For example:
``` 
$ curl -L 'https://github.com/ktr0731/evans/releases/download/0.6.11/evans_linux_amd64.tar.gz' | tar xvzf -
$ file evans
evans: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
$ mv evans /usr/local/bin/evans # This path must be included in $PATH

**Comment by abhilash93** [comment] 2019-02-20 06:16
Thank you for your help. The above steps worked.

evans --cli -r --verbose -t --host XXX.XX.XX.XX -p XXXX
evans: load global config from /root/.config/evans
evans: local config is not found
evans: bind flagset to the loaded config


I am getting the above error when run the command.

Is there any way to pass the trust store/CARoot.crt with -t option

**Comment by ktr0731** [comment] 2019-02-20 06:47
Your welcome :)
Currently, Evans supports limited TLS communication. So you cannot specify CA certificates.
However, it is supported in the next version which will be released nearly future.

**Comment by abhilash93** [comment] 2019-02-20 14:32
Oh Great!! It will be great feature for this tool. Thank you.

I have tried running this against non SSL grpc server with reflection enable but still getting the same error.

evans --cli -r --verbose --host XXX.XX.XX.XX -p XXXX
evans: load global config from /root/.config/evans
evans: local config is not found
evans: bind flagset to the loaded config

Is there something I am doing wrong?

**Comment by ktr0731** [comment] 2019-02-20 15:02
What is the mode you want to use?  
If you want to use CLI-mode, you need to specify also `--service` and `--call` options. If you want to use Evans interactively, you need to launch Evans with `--repl` option (it is omittable because it is the default mode of Evans).

For example:
```
# call SayHello method of ExampleService with input from stdin
$ echo '{"name": "foo"}' | evans -r --service ExampleService --call SayHello --host xx.xx.xx.xx --port xxxx

# launch REPL to communicate with the gRPC server
$ evans -r --host xx.xx.xx.xx --port xxxx
```

**Comment by abhilash93** [comment] 2019-02-20 15:22
I want evans interactively, but get same error local config not found

evans -r --verbose --host xx.xx.xx.xx -p xxxx
evans: load global config from /root/.config/evans
evans: local config is not found
evans: bind flagset to the loaded config

**Comment by ktr0731** [comment] 2019-02-20 15:26
If a Evans config file doesn't exsist in a project root, Evans ignore it (but only prints warning message "local config is not found").
So, please ignore it, it's an expected behavior.

**Comment by abhilash93** [comment] 2019-02-20 15:52
It looks like not able to connect to grpc server. 

I am able to telnet to the IP and port.

Is there any more logs that we can verify if connection is not establishing.

**Comment by ktr0731** [comment] 2019-02-21 03:16
If Evans couldn't connect to the gRPC server, it prints error logs to stderr regardless of the `--verbose` flag.
Could you show me error logs of the result of executing Evans without `--verbose` flag?

**Comment by ktr0731** [comment] 2019-02-23 04:41
TLS communication is now supported the latest version.

**Closed** 2019-02-23 05:54 UTC
Labels: question
