### ISSUE TITLE
helloworld.greeter.SayHello got INTERNAL_ERROR

### ISSUE THREAD

**Issue by RaymondKYLiu** [ktr0731/evans#42] opened 2018-04-19 09:39 UTC
Thanks for your awesome gRPC tool.

I build the gRPC example https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld
And run up the greeter_server, but I got an `INTERNAL_ERROR` code returned from evans.
![screenshot from 2018-04-19 17-35-37](https://user-images.githubusercontent.com/10559371/38983936-1798b380-43f8-11e8-8cc7-536a3cd917d9.png)

I am sure the server is running up, because I test with greeter_client.

Evans version: 0.2.8
OS Platform: Ubuntu 16.04, MacOS High Sierra 10.13.3
gRPC Version: v1.10.0

**Comment by ktr0731** [comment] 2018-04-20 00:04
thanks for pointing out an issue.
I'll investigate the cause but before it, can you tell me about these questions?
- the gRPC server has recorded some error log?
- at all times, Evans returns this error?

**Comment by RaymondKYLiu** [comment] 2018-04-20 01:34
* No error log recorded from gRPC server.
* Yes, always return this error. `rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR`

**Comment by acomagu** [comment] 2018-04-23 23:45
It shows the gRPC server returns `INTERNAL ERROR` so we should try another tool to know which it is wrong.
@RaymondKYLiu Did you tried [Polyglot](https://github.com/grpc-ecosystem/polyglot) or something like that?

**Comment by RaymondKYLiu** [comment] 2018-04-24 02:00
I have try another gRPC tools: omgRPC and grpcc, and they works.

**Comment by ktr0731** [comment] 2018-04-25 13:40
@RaymondKYLiu 
it seems to occur when a gRPC request has headers greater than one.
a temporarily solution is to remove `user-agent: evans` header config from `~/.config/evans/config.toml`.
after your comment has arrived, I'll close this issue and create the more described issue.

**Comment by RaymondKYLiu** [comment] 2018-05-04 17:40
@ktr0731 
Thanks, this problem is not occurring.
Solution: comment the header
```
  [[request.header]]
   # key = "user-agent"
   # val = "evans"
```

**Comment by ktr0731** [comment] 2018-05-05 03:59
ok, looks good. and I created new issue related to this problem.
so, I close this issue.

**Closed by ktr0731** 2018-05-05 03:59 UTC
