### ISSUE TITLE
evans with tls

### ISSUE THREAD

**Issue by sfm1977** [ktr0731/evans#182] opened 2019-07-25 15:19 UTC
HI,
How to use evans with tls? My gRPC server is configured to use tls, and i'm trying like this:

> `evans --tls --cert ca.crt --certkey ca.key -r --verbose 
evans: load global config from /home/sergiofm/.config/evans
evans: local config is not found
evans: bind flagset to the loaded config
evans: the conclusive config: &config.Config{
  Default: &config.Default{
    ProtoPath: []string{},
    ProtoFile: []string{},
    Package:   "",
    Service:   "",
  },
  Meta: &config.Meta{
    ConfigVersion: "0.8.0",
    AutoUpdate:    false,
    UpdateLevel:   "patch",
  },
  REPL: &config.REPL{
    PromptFormat:      "{package}.{sevice}@{addr}:{port}",
    InputPromptFormat: "{ancestor}{name} ({type}) => ",
    ColoredOutput:     true,
    Silent:            false,
    SplashTextPath:    "",
    HistorySize:       100,
  },
  Server: &config.Server{
    Host:       "127.0.0.1",
    Port:       "50051",
    Reflection: true,
    TLS:        true,
    Name:       "",
  },
  Log: &config.Log{
    Prefix: "evans: ",
  },
  Request: &config.Request{
    Header: {
      "grpc-client": []string{
        "evans",
      },
    },
    Web:         false,
    CACertFile:  "",
    CertFile:    "ca.crt",
    CertKeyFile: "ca.key",
  },
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9b0796]

goroutine 1 [running]:
github.com/ktr0731/evans/idl/proto.LoadByReflection(0x0, 0x0, 0x0, 0x0, 0x0, 0x6)
	/go/src/github.com/ktr0731/evans/idl/proto/proto.go:155 +0x26
github.com/ktr0731/evans/mode.newSpec(0xc000228450, 0x0, 0x0, 0x1, 0x1, 0xc0002d0c60, 0x50)
	/go/src/github.com/ktr0731/evans/mode/common.go:16 +0x7c
github.com/ktr0731/evans/mode.RunAsREPLMode(0xc000228450, 0xd68a80, 0xc0002cacf0, 0xc000294a00, 0x0, 0x0)
	/go/src/github.com/ktr0731/evans/mode/repl.go:28 +0x102
github.com/ktr0731/evans/app.(*App).run(0xc00000dee0, 0xc000030090, 0x7, 0x7, 0x0, 0x0)
	/go/src/github.com/ktr0731/evans/app/app.go:123 +0x453
github.com/ktr0731/evans/app.(*App).Run(0xc00000dee0, 0xc000030090, 0x7, 0x7, 0xc00000dec0)
	/go/src/github.com/ktr0731/evans/app/app.go:40 +0x4d
main.main()
	/go/src/github.com/ktr0731/evans/main.go:11 +0xc6
`

**Comment by ktr0731** [comment] 2019-07-25 17:15
Thanks for reporting the issue! This problem has been resolved in #183.

**Closed by ktr0731** 2019-07-25 17:15 UTC

**Comment by sfm1977** [comment] 2019-07-26 10:23
Hi, 

If i had CACertFile i get the same error:

 evans --tls --cert certs/server.crt --certkey certs/server.key --cacert certs/server.csr --host localhost -r --verbose
evans: load global config from /home/sergiofm/.config/evans
evans: migrated the global config to the structure of the latest version
evans: local config is not found
evans: bind flagset to the loaded config
evans: the conclusive config: &config.Config{
  Default: &config.Default{
    ProtoPath: []string{},
    ProtoFile: []string{},
    Package:   "",
    Service:   "",
  },
  Meta: &config.Meta{
    ConfigVersion: "0.8.0",
    AutoUpdate:    false,
    UpdateLevel:   "patch",
  },
  REPL: &config.REPL{
    PromptFormat:      "{package}.{sevice}@{addr}:{port}",
    InputPromptFormat: "{ancestor}{name} ({type}) => ",
    ColoredOutput:     true,
    Silent:            false,
    SplashTextPath:    "",
    HistorySize:       100,
  },
  Server: &config.Server{
    Host:       "localhost",
    Port:       "50051",
    Reflection: true,
    TLS:        true,
    Name:       "",
  },
  Log: &config.Log{
    Prefix: "evans: ",
  },
  Request: &config.Request{
    Header: {
      "grpc-client": []string{
        "evans",
      },
    },
    Web:         false,
    CACertFile:  "certs/server.csr",
    CertFile:    "certs/server.crt",
    CertKeyFile: "certs/server.key",
  },
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9fd9f8]

goroutine 1 [running]:
github.com/ktr0731/evans/mode.RunAsREPLMode(0xc0002581b0, 0xd68a60, 0xc0002c8780, 0xc0001c9630, 0x0, 0x0)
	/go/src/github.com/ktr0731/evans/mode/repl.go:23 +0x88
github.com/ktr0731/evans/app.(*App).run(0xc0000a7ee0, 0xc0000c8010, 0xb, 0xb, 0x0, 0x0)
	/go/src/github.com/ktr0731/evans/app/app.go:123 +0x453
github.com/ktr0731/evans/app.(*App).Run(0xc0000a7ee0, 0xc0000c8010, 0xb, 0xb, 0xc0000a7ec0)
	/go/src/github.com/ktr0731/evans/app/app.go:40 +0x4d
main.main()
	/go/src/github.com/ktr0731/evans/main.go:11 +0xc6

**Comment by ktr0731** [comment] 2019-07-26 10:58
I'm sorry, I had a mistake. I just fixed the problem so could you update Evans to the latest?

**Comment by sfm1977** [comment] 2019-07-26 11:31
Did that, the panic disappeared, but it's not working form me:

evans --tls --cert certs/server.crt --certkey certs/server.key --cacert certs/server.csr --host localhost -r --verbose
evans: load global config from /home/sergiofm/.config/evans
evans: migrated the global config to the structure of the latest version
evans: local config is not found
evans: bind flagset to the loaded config
evans: the conclusive config: &config.Config{
  Default: &config.Default{
    ProtoPath: []string{},
    ProtoFile: []string{},
    Package:   "",
    Service:   "",
  },
  Meta: &config.Meta{
    ConfigVersion: "0.8.0",
    AutoUpdate:    false,
    UpdateLevel:   "patch",
  },
  REPL: &config.REPL{
    PromptFormat:      "{package}.{sevice}@{addr}:{port}",
    InputPromptFormat: "{ancestor}{name} ({type}) => ",
    ColoredOutput:     true,
    Silent:            false,
    SplashTextPath:    "",
    HistorySize:       100,
  },
  Server: &config.Server{
    Host:       "localhost",
    Port:       "50051",
    Reflection: true,
    TLS:        true,
    Name:       "",
  },
  Log: &config.Log{
    Prefix: "evans: ",
  },
  Request: &config.Request{
    Header: {
      "grpc-client": []string{
        "evans",
      },
    },
    Web:         false,
    CACertFile:  "certs/server.csr",
    CertFile:    "certs/server.crt",
    CertKeyFile: "certs/server.key",
  },
}
evans: failed to run REPL mode: failed to instantiate a new gRPC client: failed to instantiate a gRPC client: failed to append the client certificate

Any idea?

**Comment by ktr0731** [comment] 2019-07-26 11:47
Did you pass a valid root CA certificate?
The error is caused by https://golang.org/pkg/crypto/x509/#CertPool.AppendCertsFromPEM.

**Comment by sfm1977** [comment] 2019-07-26 14:52
Thanks, i'm going to spend more time with this subject...

**Comment by sfm1977** [comment] 2019-07-26 15:32
Got it here, if anyone gets the same problem...
https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309
