### ISSUE TITLE
Chaos input when pressed some comb-key

### ISSUE THREAD

**Issue by coanor** [ktr0731/evans#335] opened 2020-12-04 10:36 UTC
I'm using Iterm2 on Mac(10.14.6). When Pressing some comb-key like `left+up`, the UI display(occasionally) like this:

```
BrBrBrowsBrowsBrBrBrBrowBrowBrBroBroBroBrowserPerfService@127.0.0.1:50051> ?[?[D?[AD
```

Now, all my ascii input, include backspace, display like this:

```
BrBrBrowsBrowsBrBrBrBrowBrowBrBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBroBrowserPerfService@127.0.0.1:50051> ?[?[D?aaaaaD
```

I have to use `ctrl + l` to clean the chaos output, then I get the expected display:

```
BrowserPerfService@127.0.0.1:50051>
```

Is this a bug(maybe a `go-prompt` package bug)? I thinks frequently pressing `left` and `up` is ok to edit exists input, but it's too easy to press them at the same time, then the display crached.

**Comment by ktr0731** [comment] 2020-12-09 14:08
Hi, @coanor.
It may be `c-bata/go-prompt`'s bug. Actually, it reproduced in [an example of `c-bata/go-prompt`](https://github.com/c-bata/go-prompt/tree/master/_example/simple-echo).

**Comment by ktr0731** [comment] 2020-12-09 14:12
I submitted an issue about this.
https://github.com/c-bata/go-prompt/issues/213

**Comment by ktr0731** [comment] 2021-04-06 06:45
Since this is a bug in a dependent package, we'll close this PR for now. We'll re-open after the bug is fixed.

**Closed by ktr0731** 2021-04-06 06:45 UTC
Labels: bug
